### Practical_6: Numpy

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

In [4]:
import numpy as np
b= np.arange(1, 11)
print(b)


[ 1  2  3  4  5  6  7  8  9 10]


### Exercise 2

Create a 3x3 NumPy array filled with zeros.

In [20]:
import numpy as np
array_zeros = np.zeros((3, 3))
print(array_zeros)
b.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('int32')

### Exercise 3
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

In [68]:
import numpy as np
print("\n")
a=np.linspace(0,5,10)
print(a1)




[0 1 2 3 4 5]


### Exercise 4:
Create a 5x5 identity matrix using NumPy.

In [24]:
a=np.eye(5,5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Exercise 5

Create a 4x4 matrix with random values between 0 and 1.

In [42]:

b=np.random.random((4,4))
b


array([[0.58194701, 0.27952398, 0.72624737, 0.95755123],
       [0.93188188, 0.79290003, 0.839266  , 0.47357899],
       [0.40611447, 0.563047  , 0.60260089, 0.8781133 ],
       [0.90658027, 0.87289269, 0.45201018, 0.08638128]])

### Exercise 6

Find the shape of a NumPy array.

In [197]:
import numpy as np

array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9],
                  [10,11,12],])
shape = array.shape
print("Shape of the array:", shape)

Shape of the array: (4, 3)


### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

In [209]:
import numpy as np

array_1D = np.arange(1, 17)  
matrix_4x4 = array_1D.reshape((4, 4))
print("Original 1D Array:")
print(array_1D)
print("\nReshaped 4x4 Matrix:")
print(matrix_4x4)

Original 1D Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]

Reshaped 4x4 Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


### Exercise 8:
Find the data type of the elements in a NumPy array.

In [213]:
import numpy as np
array = np.array([1, 2, 3, 4, 5])  
data_type = array.dtype
print("Data type of the array:", data_type)

Data type of the array: int32


### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

In [52]:
a=np.arange(1,101)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])


### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

In [66]:
a=np.random.randint(10,50,(6,6))
a

array([[22, 25, 46, 38, 46, 39],
       [44, 31, 39, 30, 25, 14],
       [35, 21, 41, 47, 25, 18],
       [44, 15, 15, 34, 12, 36],
       [42, 42, 37, 41, 10, 27],
       [41, 23, 15, 29, 19, 38]])

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

In [189]:
import numpy as np

matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

submatrix = matrix[1:3, 1:3] 
print("Original Matrix:")
print(matrix)
print("\nSubmatrix:")
print(submatrix)

Original Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Submatrix:
[[ 6  7]
 [10 11]]


### Exercise 12:
Calculate the sum of all elements in a NumPy array.

In [87]:
import numpy as np
array = np.arange(1, 11)
sum_of_elements = np.sum(array)
print("Sum of all elements:", sum_of_elements)
           

Sum of all elements: 55


### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

In [96]:
array = np.arange(10) 
print(array) 
     # meanof array
a1 = np.mean(array) 
print("\nMean: ", a1) 
  
     # standard deviation 
a2= np.std(array) 
print("\nstd: ", a2) 
  
     # variance
a3 = np.var(array) 
print("\nvariance: ", a3) 

[0 1 2 3 4 5 6 7 8 9]

Mean:  4.5

std:  2.8722813232690143

variance:  8.25


### Exercise 14
Find the maximum and minimum values in a NumPy array.

In [107]:
array= np.arange(10)
print(array)
minimum_elements= np.max(array)
maximum_elements= np.min(array)



[0 1 2 3 4 5 6 7 8 9]


### Exercise 15
Create a NumPy array of 20 random integers and find the index of the maximum value.

In [148]:
import numpy as np
np.random.seed()
a=np.random.randint(10,size=20)
print(a)


[1 0 1 9 1 2 6 0 7 4 1 3 5 0 9 7 8 2 3 8]


### Exercise 16
Create a NumPy array and reverse its elements.

In [168]:
import numpy as np

array1 = np.array([0, 2, 4, 6, 4, 5])
array2=np.flip(array1)
print("array2", str(array2))


array2 [5 4 6 4 2 0]


### Exercise 17
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

In [172]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]],)
y = np.array([[1,2,3],[4,5,6],[7,8,9]],)
print(x*y)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


### Exercise 18
Create a diagonal matrix from a given 1D array.

In [187]:
import numpy as np

array_1D = np.array([1, 2, 3, 4, 5])
diagonal_matrix = np.diag(array_1D)
print("Diagonal Matrix:")
print(diagonal_matrix)

Diagonal Matrix:
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

In [181]:
import numpy as np
matrix_a = np.array([[1, 2, 3],
                      [4, 5, 6]])

matrix_b = np.array([[7, 8],
                      [9, 10],
                      [11, 12]])
result = np.dot(matrix_a, matrix_b) 
print("Result of matrix multiplication:")
print(result)

Result of matrix multiplication:
[[ 58  64]
 [139 154]]


### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

In [184]:
import numpy as np

ini_array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print("initial array", str(ini_array1))
result = ini_array1.flatten()
print("New resulting array: ", result)


initial array [[1 2 3]
 [2 4 5]
 [1 2 3]]
New resulting array:  [1 2 3 2 4 5 1 2 3]
